### PR TITLE
bug 1821667: runtimecfg: tool to show the Virtual Router IDs

### PR DESCRIPTION
**Pull request by celebdor**
With this tool, an operator will be able to easily determine before
deployment if the cluster names chosen will end up with conflicting
Virtual Router IDs. One can't use the same Virtual Router ID for
different VIPs in the same multicast domain.

Usage example:

    $ ./runtimecfg vr-ids cnf10
    APIVirtualRouterID: 147
    DNSVirtualRouterID: 158
    IngressVirtualRouterID: 2
    $ ./runtimecfg vr-ids cnf11
    APIVirtualRouterID: 228
    DNSVirtualRouterID: 239
    IngressVirtualRouterID: 147

In this example, we can see that cluster cnf10 would end up with the
API virtual router id conflicting with cnf11's ingress router id. In
this case, if both clusters share the same control plane multicast
domain, different cluster names should be chosen.

### CODE REVIEW

**Comment by yboaron** [comment]
code looks good, I'll LGTMEd after I verify that deployment with baremetal image

**Comment by cybertron** [comment]
/test e2e-metal-ipi

Note that we have a ci job on this repo now so manual verification shouldn't be needed.

The change also lgtm.

**Comment by yboaron** [comment]
run deployment locally - looks OK.

**Comment by yboaron** [comment]
/retitle bug 1821667: runtimecfg: tool to show the Virtual Router IDs

**Pull request merged**
