### PR TITLE
Bug 1995468: CoreDNS Corefile hosts - add support for dual-stack

### PR DESCRIPTION
**Pull request by yboaron**
In case of dual-stack deployment, both IPV4 and IPV6 addresses assigned to a node,
CoreDNS should resolve hostname for both addresses.

### CODE REVIEW

**Comment by yboaron** [comment]
/retitle Bug 1995468: CoreDNS Corefile hosts - add support for dual-stack

**Comment by cybertron** [comment]
/retest

I deployed this locally and confirmed it's doing the right thing:

hosts {
        192.168.111.20 master-0 master-0.ostest.test.metalkube.org
        fd2e:6f44:5dd8:c956::14 master-0 master-0.ostest.test.metalkube.org
        192.168.111.21 master-1 master-1.ostest.test.metalkube.org
        fd2e:6f44:5dd8:c956::15 master-1 master-1.ostest.test.metalkube.org
        192.168.111.22 master-2 master-2.ostest.test.metalkube.org
        fd2e:6f44:5dd8:c956::16 master-2 master-2.ostest.test.metalkube.org
        192.168.111.23 worker-0 worker-0.ostest.test.metalkube.org
        fd2e:6f44:5dd8:c956::17 worker-0 worker-0.ostest.test.metalkube.org
        192.168.111.24 worker-1 worker-1.ostest.test.metalkube.org
        fd2e:6f44:5dd8:c956::18 worker-1 worker-1.ostest.test.metalkube.org
        fallthrough
    }

[root@master-0 coredns]# ping master-1
PING master-1(master-1 (fd2e:6f44:5dd8:c956::15)) 56 data bytes
...
[root@master-0 coredns]# ping -4 master-1
PING master-1.ostest.test.metalkube.org (192.168.111.21) 56(84) bytes of data.

Both addresses are present and resolve.
/lgtm

**Pull request merged**
