### PR TITLE
Bug 1949859: Add Ironic healthcheck to bootstrap keepalived checks

### PR DESCRIPTION
**Pull request by cybertron**
Ironic has started using the API VIP for access, and as a result we
need to keep the VIP available when Ironic is. The apiserver can go
down periodically during bootstrapping, so that isn't a reliable way
to keep the VIP alive on its own.

This change adds another check when the apiserver check fails. It
will ping Ironic and if Ironic is still up then it won't count the
check as failed and will keep the VIP active.

Note that previously Ironic was never stopped on the boostrap node.
Doing that will be a pre-requisite to this functionality as we do
need to allow keepalived to stop once bootstrapping is complete so
the VIP moves to the masters. Since bootstrapping can't complete
until after Ironic has provisioned the masters, if we stop Ironic
after provisioning then this check won't prevent VIP migration when
bootstrap is complete.

### CODE REVIEW

**Comment by cybertron** [comment]
/hold

This won't work without changes to the Ironic lifecycle on the boostrap node.

**Comment by stbenjam** [comment]
/retitle Bug 1949859: Add Ironic healthcheck to bootstrap keepalived checks

**Comment by cybertron** [comment]
Once https://github.com/openshift/installer/pull/4900 merges this should pass ci.

**Comment by hs0210** [comment]
Manually merging [#135](https://github.com/openshift/baremetal-runtimecfg/pull/135) and [#4900](https://github.com/openshift/installer/pull/4900), I did several IPI tests, this problem did not reappear.

**Comment by zhouhao3** [comment]
https://github.com/openshift/installer/pull/4900  has been merged. It seems that this PR needs a retest.

**Comment by rhjanders** [comment]
Thank you @zhouhao3, just requested retest.

**Comment by rhjanders** [comment]
/recheck again just to see if we get the same failures again

**Pull request merged**
