### PR TITLE
OCPBUGS-673: Apply ipv6 bind check to non-VIP case too

### PR DESCRIPTION
**Pull request by cybertron**
Backport of the two patches needed to make the ipv6 bind check work on UPI platforms too.

### CODE REVIEW

**Comment by cybertron** [comment]
@dougsland @reihl Please take a look at this backport.

**Review by dougsland — APPROVED** [review]
/lgtm

**Comment by cybertron** [comment]
/label backport-risk-assessed

@reihl We still need cherry-pick-approved too.

**Comment by creydr** [comment]
> /cherry-pick-approved

@reihl, It looks like the bot didn't take that. You think you have to do `/label cherry-pick-approved`

**Pull request merged**
