### PR TITLE
Bug 2086483: Update k8s dependencies to 1.24

### PR DESCRIPTION
**Pull request by creydr**
Updated to Golang 1.18 and kubernetes dependencies to 1.24

### CODE REVIEW

**Comment by cybertron** [comment]
/lgtm
/hold

Once ci is passing anyone should feel free to remove the hold. I would ideally like to see the optional job pass too.

**Comment by cybertron** [comment]
It looks like there are issues with the metal-ipi ci jobs right now. This is probably going to need a bug associated so it can go in next week. :-/

**Comment by creydr** [comment]
/title Bug 2086483: Update k8s dependencies to 1.24

**Comment by creydr** [comment]
/retitle Bug 2086483: Update k8s dependencies to 1.24

**Comment by amalykhi** [comment]
/lgtm
go.mod verified

**Pull request merged**
