### PR TITLE
Remove get boostrap IP code

### PR DESCRIPTION
**Pull request by yboaron**
Since we eliminate the need for the master nodes to know the bootstrap IP address
for unicast Keepalived, we can delete the code that implements this functionality.

Depends on : [MCO PR](https://github.com/openshift/machine-config-operator/pull/2185)

### CODE REVIEW

**Comment by yboaron** [comment]
e2e-metal-ipi gate is red because https://github.com/openshift/machine-config-operator/pull/2185 wasn't merged yet.

**Review by cybertron — APPROVED** [review]
Once the MCO patch is in and ci is passing this lgtm.

**Pull request merged**
