### PR TITLE
Bug 1995021: upgrade k8s.io/client-go

### PR DESCRIPTION
**Pull request by yboaron**
We noticed that after VIP switchover coredns-monitor is stuck on get nodes code [1] for ~20 minutes, upgrade k8s.io/client-go fixed this issue. 

[1] https://github.com/openshift/baremetal-runtimecfg/blob/master/pkg/config/node.go#L455

### CODE REVIEW

**Comment by cybertron** [comment]
/lgtm

Paging the ci bot...

**Comment by yboaron** [comment]
This PR solves one of the regression tests that constantly fail in QE, checking if auto cherry-pick is possible here
/cherry-pick release-4.9

**Pull request merged**
