### PR TITLE
Add mandre and tsorya as approvers

### PR DESCRIPTION
**Pull request by cybertron**
We are perpetually short on approvers for this repo because the team keeps changing. Martin and Igal have done quite a bit of work in and related to this repo so I would be comfortable with them approving changes, especially if we're in a situation where our on-prem networking approver(s) are not available.

I'm not adding them to the reviewers list because I doubt they want to be auto-assigned to patches here, but I'm happy to change that if I'm wrong. :-)

### CODE REVIEW

**Comment by cybertron** [comment]
/cc @mandre @tsorya 

Let me know if you're okay with this. I'm not expecting you to review patches regularly, but I want to have more than just the couple of people in the on-prem team on the list so we don't end up stuck if one or both of us are unavailable for some reason.

**Comment by dougsland** [comment]
> /cc @mandre @tsorya
> 
> Let me know if you're okay with this. I'm not expecting you to review patches regularly, but I want to have more than 
> just the couple of people in the on-prem team on the list so we don't end up stuck if one or both of us are unavailable
> for some reason.

waiting for the lgtm

**Comment by mandre** [comment]
All good on my side :+1:

**Comment by tsorya** [comment]
Works for me

**Comment by creydr** [comment]
/lgtm
I will create a PR to remove myself after this merged

**Pull request merged**
