### PR TITLE
OCPBUGS-14936: node: remove duplicate

### PR DESCRIPTION
**Pull request by rbbratta**

### CODE REVIEW

**Review by mkowalski — APPROVED** [review]

**Comment by cybertron** [comment]
/lgtm

I guess we still need bugs to merge anything to master.

**Comment by rbbratta** [comment]
OCPBUGS-14936

**Comment by mkowalski** [comment]
/retitle OCPBUGS-14936: node: remove duplicate

(note the colon after Jira card; bot's regex needs it)

**Pull request merged**
