### PR TITLE
Add test target for CI

### PR DESCRIPTION
**Pull request by bcrochet**
This adds a Makefile target for CI to run unit tests

### CODE REVIEW

**Comment by yboaron** [comment]
@bcrochet 

I checked this PR locally, is this the output you expect to see?


[root@dfdfdf baremetal-runtimecfg]# make test 
go test ./pkg/... ./cmd/...
?       github.com/openshift/baremetal-runtimecfg/pkg/config    [no test files]
?       github.com/openshift/baremetal-runtimecfg/pkg/monitor   [no test files]
?       github.com/openshift/baremetal-runtimecfg/pkg/render    [no test files]
?       github.com/openshift/baremetal-runtimecfg/pkg/utils     [no test files]
?       github.com/openshift/baremetal-runtimecfg/cmd/dynkeepalived     [no test files]
?       github.com/openshift/baremetal-runtimecfg/cmd/monitor   [no test files]
?       github.com/openshift/baremetal-runtimecfg/cmd/runtimecfg        [no test files]
[root@dfdfdf baremetal-runtimecfg]#

**Comment by bcrochet** [comment]
> @bcrochet
> 
> I checked this PR locally, is this the output you expect to see?
> 
> [root@dfdfdf baremetal-runtimecfg]# make test
> go test ./pkg/... ./cmd/...
> ? github.com/openshift/baremetal-runtimecfg/pkg/config [no test files]
> ? github.com/openshift/baremetal-runtimecfg/pkg/monitor [no test files]
> ? github.com/openshift/baremetal-runtimecfg/pkg/render [no test files]
> ? github.com/openshift/baremetal-runtimecfg/pkg/utils [no test files]
> ? github.com/openshift/baremetal-runtimecfg/cmd/dynkeepalived [no test files]
> ? github.com/openshift/baremetal-runtimecfg/cmd/monitor [no test files]
> ? github.com/openshift/baremetal-runtimecfg/cmd/runtimecfg [no test files]
> [root@dfdfdf baremetal-runtimecfg]#

Yes it is, since there are no unit tests yet. :)

**Comment by cybertron** [comment]
/assign celebdor

Turns out I'm not an approver on this repo. :-)

**Pull request merged**
