### PR TITLE
[release-4.11] OCPBUGS-15539: Use machine-config state instead of comparing roles

### PR DESCRIPTION
**Pull request by cybertron**
This is a manual cherry-pick of #262 . It appears the backport was not clean simply due to whitespace changes.

### CODE REVIEW

**Comment by cybertron** [comment]
/label backport-risk-assessed

Will it let me do this on my own PR?

**Comment by cybertron** [comment]
@qiowang721 Can you give this cherry-pick-approved? Thanks!

**Review by mkowalski — APPROVED** [review]

**Pull request merged**
