### PR TITLE
Bug 1872080: Add Dockerfile.openshift for CI

### PR DESCRIPTION
**Pull request by bcrochet**
We want to use this Dockerfile for CI so that local builds will continue
to use the ubi8 image.

### CODE REVIEW

**Comment by cybertron** [comment]
So this would be used for ci and product builds as defined by https://github.com/openshift/ocp-build-data/blob/openshift-4.6/images/baremetal-runtimecfg.yml right? Should this be called Dockerfile.openshift instead, since we're already using a rhel8-based image in the regular Dockerfile?

**Comment by bcrochet** [comment]
> So this would be used for ci and product builds as defined by https://github.com/openshift/ocp-build-data/blob/openshift-4.6/images/baremetal-runtimecfg.yml right? Should this be called Dockerfile.openshift instead, since we're already using a rhel8-based image in the regular Dockerfile?

Don't care what it's called. Dockerfile.openshift does work better for me.

**Comment by cybertron** [comment]
/lgtm

Looks like we will need a bug for this to merge.

**Comment by bcrochet** [comment]
/retitle Bug 1872080: Add Dockerfile.openshift for CI

**Pull request merged**
